s3:
  bucket:
    name: miristudy
  object:
    base:
      path: object/

spring:
  datasource:
    url: jdbc:postgresql://miristudy2.c5jruzsds8gc.ap-northeast-2.rds.amazonaws.com/miristudy_db
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: localhost