s3:
  bucket:
    name: miristudy
  object:
    base:
      path: object/

spring:
  datasource:
    url: jdbc:postgresql://miristudy-db.cktwssh86hz5.ap-northeast-2.rds.amazonaws.com/miristudy_db
  jpa:
    show-sql: true

server:
  port: 5000
